# metadata
run_name: 'map'
logging: 'True'


# map paths
map_path: 'IMS/IMS_map'
map_ext: '.png'

# Before Start\ Finish Line: 5.5572091; 0.6514429; 3.4033109
# Start\ Finish Line: -0.0440806;-0.8491629;3.4034118;
# T1 (Niki Lauda): -26.8810112; -8.0811682; 3.3949863;
# T2 (Remus): -72.7851387; 47.1581236; 2.3546648
# Middle section: -51.7582509;52.9369422;6.1060188;
# T3 (Schlossgold):
# T4 (Rauch):
# T5 (Wuerth): -44.1425135;20.8809411;5.3546563
# T7 (Rindt):

#parameters for reset
sx: 0
sy:  5
stheta: -1.7


# raceline path and indices
wpt_path: 'IMS/IMS_raceline.csv'
wpt_path2: 'IMS/IMS_centerline.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2

