# metadata
run_name: 'map_wide'
logging: 'True'
# characteristic number for map
perf_num: 6

# map paths
map_path: 'obstacle_map/new_spielberg'
map_ext: '.png'

# Before Start\ Finish Line: 5.5572091; 0.6514429; 3.4033109
# Start\ Finish Line: -0.0440806;-0.8491629;3.4034118;
# T1 (Niki Lauda): -26.8810112; -8.0811682; 3.3949863;
# T2 (Remus): -72.7851387; 47.1581236; 2.3546648
# Middle section: -51.7582509;52.9369422;6.1060188;
# T3 (Schlossgold):
# T4 (Rauch):
# T5 (Wuerth): -44.1425135;20.8809411;5.3546563
# T7 (Rindt):

#parameters for reset
sx: -0.0440806
sy:  -0.8491629
stheta: 3.4034118

#parameters for second car
sx2: -30.0440806
sy2:  -7.8491629
stheta2: 3.4034118


# raceline path and indices
wpt_path: 'map/Spielberg_raceline.csv'
wpt_path2: 'map/Spielberg_centerline.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# seed
seed: 12345